version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: maersk-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  maersk-booking-service:
    build: .
    container_name: maersk-booking-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/maerskdb

volumes:
  mongo_data: